name: "iptables loadbalancer - CNI: kindnetd"
on:
  workflow_dispatch:
  schedule:
    # Daily, 3:00pm
    - cron: '00 15 * * *'

jobs:
  iptables-loadbalancer-cni-kindnetd:
    runs-on: [ ubuntu-18.04 ]
    steps:
      - uses: actions/checkout@v2
        with:
           path: main

          # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.0' # The Go version to download (if necessary) and use.
    
      - uses: actions/checkout@master
        with:
          repository: K8sbykeshed/k8s-local-dev
          path: k8s-local-dev

      - run: |
          pushd ./k8s-local-dev
            ./k8s-local-dev kindnetd
          popd
          pushd ./main
            mkdir -p downloads
            go get github.com/thekubeworld/k8devel
            go get github.com/gookit/color
            go get github.com/sirupsen/logrus
            pushd ./tests/loadbalancer/
               go run main.go &> ../../downloads/output_kubeproxy_iptables_loadbalancer.log
            popd
          popd
      - uses: actions/upload-artifact@v2
        with:
          name: logs
          path: ./main/downloads/
          retention-days: 60
