name: "iptables kubeproxy clusterip - CNI: kindnetd"
on:
  workflow_dispatch:
  schedule:
    # Daily, 3:00pm
    - cron: '00 15 * * *'

jobs:
  iptables-kubeproxy-clusterip-cni-kindnetd:
    runs-on: [ ubuntu-18.04 ]
    steps:
      - uses: actions/checkout@v2
        with:
           path: main

        # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0' # The Go version to download (if necessary) and use.
      - uses: actions/checkout@master
        with:
          repository: thekubeworld/k8s-local-dev
          path: k8s-local-dev
      - run: |
          pushd ./k8s-local-dev
            ./k8s-local-dev kindnetd
          popd
          pushd ./main
            mkdir -p downloads
            echo "GO111MODULE=auto" >> $GITHUB_ENV
            go get github.com/thekubeworld/k8devel/pkg/client 
            go get github.com/gookit/color
            go get github.com/sirupsen/logrus
            go build ./tests/clusterip/main.go #&> downloads/output_kubeproxy_iptables_clusterip.log
          popd
      - uses: actions/upload-artifact@v2
        with:
          name: logs
          path: ./main/downloads/
          retention-days: 60
