name: "ipvs kubeproxy loadbalancer - CNI: kindnetd"
on:
  workflow_dispatch:
  schedule:
    # Daily, 3:00pm
    - cron: '00 15 * * *'

jobs:
  ipvs-kubeproxy-loadbalancer-cni-kindnetd:
    runs-on: [ ubuntu-18.04 ]
    GOPATH: /home/runner/work/k8devel/go
    GO111MODULE: auto
    steps:
      - uses: actions/checkout@v2
        with:
           path: main

          # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'
    
      - uses: actions/checkout@master
        with:
          repository: thekubeworld/k8s-local-dev
          path: k8s-local-dev

      - run: |
          pushd ./k8s-local-dev
            ./k8s-local-dev kindnetd --kube-proxy-mode ipvs
          popd
          pushd ./main
            mkdir -p downloads
            go get github.com/moby/spdystream
            go get github.com/thekubeworld/k8devel/pkg/client
            go get github.com/gookit/color
            go get github.com/sirupsen/logrus
            pushd ./tests/loadbalancer/
               go run main.go &> ../../downloads/output_kubeproxy_iptables_clusterip.log
            popd
          popd
      - uses: actions/upload-artifact@v2
        with:
          name: logs
          path: ./main/downloads/
          retention-days: 60
